// Code generated by the Encore v1.53.0 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/
import type { CookieWithOptions } from "encore.dev/api";

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:4000"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-whereisit-inventory-app-9xhi.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === "object" && ("window" in globalThis);

/**
 * Client is an API client for the whereisit-inventory-app-9xhi Encore application.
 */
export class Client {
    public readonly container: container.ServiceClient
    public readonly folder: folder.ServiceClient
    public readonly household: household.ServiceClient
    public readonly image: image.ServiceClient
    public readonly item: item.ServiceClient
    public readonly location: location.ServiceClient
    public readonly shopping: shopping.ServiceClient
    private readonly options: ClientOptions
    private readonly target: string


    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions) {
        this.target = target
        this.options = options ?? {}
        const base = new BaseClient(this.target, this.options)
        this.container = new container.ServiceClient(base)
        this.folder = new folder.ServiceClient(base)
        this.household = new household.ServiceClient(base)
        this.image = new image.ServiceClient(base)
        this.item = new item.ServiceClient(base)
        this.location = new location.ServiceClient(base)
        this.shopping = new shopping.ServiceClient(base)
    }

    /**
     * Creates a new Encore client with the given client options set.
     *
     * @param options Client options to set. They are merged with existing options.
     **/
    public with(options: ClientOptions): Client {
        return new Client(this.target, {
            ...this.options,
            ...options,
        })
    }
}

/**
 * Import the auth handler to be able to derive the auth type
 */
import type { auth as auth_auth } from "~backend/auth/auth";

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    /**
     * Allows you to set the authentication data to be used for each
     * request either by passing in a static object or by passing in
     * a function which returns a new object for each request.
     */
    auth?: RequestType<typeof auth_auth> | AuthDataGenerator
}


export namespace auth {
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import {
    create as api_container_api_create,
    deleteContainer as api_container_api_deleteContainer,
    list as api_container_api_list,
    listByLocation as api_container_api_listByLocation,
    update as api_container_api_update
} from "~backend/container/api";
import { uploadPhoto as api_container_upload_photo_uploadPhoto } from "~backend/container/upload_photo";

export namespace container {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.deleteContainer = this.deleteContainer.bind(this)
            this.list = this.list.bind(this)
            this.listByLocation = this.listByLocation.bind(this)
            this.update = this.update.bind(this)
            this.uploadPhoto = this.uploadPhoto.bind(this)
        }

        public async create(params: RequestType<typeof api_container_api_create>): Promise<ResponseType<typeof api_container_api_create>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/containers`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_container_api_create>
        }

        public async deleteContainer(params: { id: string }): Promise<void> {
            await this.baseClient.callTypedAPI(`/containers/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
        }

        public async list(): Promise<ResponseType<typeof api_container_api_list>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/containers`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_container_api_list>
        }

        public async listByLocation(params: { locationId: string }): Promise<ResponseType<typeof api_container_api_listByLocation>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/locations/${encodeURIComponent(params.locationId)}/containers`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_container_api_listByLocation>
        }

        public async update(params: RequestType<typeof api_container_api_update>): Promise<ResponseType<typeof api_container_api_update>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                locationId: params.locationId,
                name:       params.name,
                photoUrl:   params.photoUrl,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/containers/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_container_api_update>
        }

        public async uploadPhoto(params: RequestType<typeof api_container_upload_photo_uploadPhoto>): Promise<ResponseType<typeof api_container_upload_photo_uploadPhoto>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/containers/upload-photo`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_container_upload_photo_uploadPhoto>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { create as api_folder_create_create } from "~backend/folder/create";

export namespace folder {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
        }

        public async create(params: RequestType<typeof api_folder_create_create>): Promise<ResponseType<typeof api_folder_create_create>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/folders`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_folder_create_create>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { acceptInvitationByCode as api_household_accept_by_code_acceptInvitationByCode } from "~backend/household/accept_by_code";
import { acceptInvitation as api_household_accept_invitation_acceptInvitation } from "~backend/household/accept_invitation";
import { cancelInvitation as api_household_cancel_invitation_cancelInvitation } from "~backend/household/cancel_invitation";
import { create as api_household_create_create } from "~backend/household/create";
import { get as api_household_get_get } from "~backend/household/get";
import { getHouseholdById as api_household_get_household_by_id_getHouseholdById } from "~backend/household/get_household_by_id";
import { getInvitations as api_household_get_invitations_getInvitations } from "~backend/household/get_invitations";
import { getMembers as api_household_get_members_getMembers } from "~backend/household/get_members";
import { getPendingInvitations as api_household_get_pending_invitations_getPendingInvitations } from "~backend/household/get_pending_invitations";
import { invite as api_household_invite_invite } from "~backend/household/invite";
import { removeMember as api_household_remove_member_removeMember } from "~backend/household/remove_member";
import { rename as api_household_rename_rename } from "~backend/household/rename";
import { resendInvitation as api_household_resend_invitation_resendInvitation } from "~backend/household/resend_invitation";

export namespace household {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.acceptInvitation = this.acceptInvitation.bind(this)
            this.acceptInvitationByCode = this.acceptInvitationByCode.bind(this)
            this.cancelInvitation = this.cancelInvitation.bind(this)
            this.create = this.create.bind(this)
            this.get = this.get.bind(this)
            this.getHouseholdById = this.getHouseholdById.bind(this)
            this.getInvitations = this.getInvitations.bind(this)
            this.getMembers = this.getMembers.bind(this)
            this.getPendingInvitations = this.getPendingInvitations.bind(this)
            this.invite = this.invite.bind(this)
            this.leave = this.leave.bind(this)
            this.removeMember = this.removeMember.bind(this)
            this.rename = this.rename.bind(this)
            this.resendInvitation = this.resendInvitation.bind(this)
        }

        public async acceptInvitation(params: RequestType<typeof api_household_accept_invitation_acceptInvitation>): Promise<ResponseType<typeof api_household_accept_invitation_acceptInvitation>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/household/accept-invitation`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_household_accept_invitation_acceptInvitation>
        }

        public async acceptInvitationByCode(params: RequestType<typeof api_household_accept_by_code_acceptInvitationByCode>): Promise<ResponseType<typeof api_household_accept_by_code_acceptInvitationByCode>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/household/accept-by-code`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_household_accept_by_code_acceptInvitationByCode>
        }

        public async cancelInvitation(params: RequestType<typeof api_household_cancel_invitation_cancelInvitation>): Promise<void> {
            await this.baseClient.callTypedAPI(`/household/cancel-invitation`, {method: "POST", body: JSON.stringify(params)})
        }

        public async create(params: RequestType<typeof api_household_create_create>): Promise<ResponseType<typeof api_household_create_create>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/household`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_household_create_create>
        }

        public async get(): Promise<ResponseType<typeof api_household_get_get>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/household`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_household_get_get>
        }

        public async getHouseholdById(params: { household_id: number }): Promise<ResponseType<typeof api_household_get_household_by_id_getHouseholdById>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/household/${encodeURIComponent(params.household_id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_household_get_household_by_id_getHouseholdById>
        }

        public async getInvitations(): Promise<ResponseType<typeof api_household_get_invitations_getInvitations>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/household/invitations`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_household_get_invitations_getInvitations>
        }

        public async getMembers(): Promise<ResponseType<typeof api_household_get_members_getMembers>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/household/members`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_household_get_members_getMembers>
        }

        public async getPendingInvitations(): Promise<ResponseType<typeof api_household_get_pending_invitations_getPendingInvitations>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/household/pending-invitations`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_household_get_pending_invitations_getPendingInvitations>
        }

        public async invite(params: RequestType<typeof api_household_invite_invite>): Promise<ResponseType<typeof api_household_invite_invite>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/household/invite`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_household_invite_invite>
        }

        public async leave(): Promise<void> {
            await this.baseClient.callTypedAPI(`/household/leave`, {method: "POST", body: undefined})
        }

        public async removeMember(params: RequestType<typeof api_household_remove_member_removeMember>): Promise<void> {
            await this.baseClient.callTypedAPI(`/household/remove-member`, {method: "POST", body: JSON.stringify(params)})
        }

        public async rename(params: RequestType<typeof api_household_rename_rename>): Promise<ResponseType<typeof api_household_rename_rename>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/household/rename`, {method: "PUT", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_household_rename_rename>
        }

        public async resendInvitation(params: RequestType<typeof api_household_resend_invitation_resendInvitation>): Promise<void> {
            await this.baseClient.callTypedAPI(`/household/resend-invitation`, {method: "POST", body: JSON.stringify(params)})
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import {
    analyze as api_image_image_analyze,
    getUploadUrl as api_image_image_getUploadUrl
} from "~backend/image/image";

export namespace image {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.analyze = this.analyze.bind(this)
            this.getUploadUrl = this.getUploadUrl.bind(this)
        }

        public async analyze(params: RequestType<typeof api_image_image_analyze>): Promise<ResponseType<typeof api_image_image_analyze>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/analyze`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_image_image_analyze>
        }

        public async getUploadUrl(params: RequestType<typeof api_image_image_getUploadUrl>): Promise<ResponseType<typeof api_image_image_getUploadUrl>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/image/upload-url`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_image_image_getUploadUrl>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { addReceipt as api_item_add_receipt_addReceipt } from "~backend/item/add_receipt";
import { analyzeBookshelf as api_item_analyze_bookshelf_analyzeBookshelf } from "~backend/item/analyze_bookshelf";
import { analyzeShelf as api_item_analyze_shelf_analyzeShelf } from "~backend/item/analyze_shelf";
import { analyzeShelfOcr as api_item_analyze_shelf_ocr_analyzeShelfOcr } from "~backend/item/analyze_shelf_ocr";
import { lookupBarcode as api_item_barcode_lookupBarcode } from "~backend/item/barcode";
import { batchCreate as api_item_batch_create_batchCreate } from "~backend/item/batch_create";
import { batchListByContainers as api_item_batch_list_by_containers_batchListByContainers } from "~backend/item/batch_list_by_containers";
import { batchListByLocations as api_item_batch_list_by_locations_batchListByLocations } from "~backend/item/batch_list_by_locations";
import { bulkAddTags as api_item_bulk_add_tags_bulkAddTags } from "~backend/item/bulk_add_tags";
import { bulkConfirmLocation as api_item_bulk_confirm_location_bulkConfirmLocation } from "~backend/item/bulk_confirm_location";
import { bulkDelete as api_item_bulk_delete_bulkDelete } from "~backend/item/bulk_delete";
import { bulkUpdateLocation as api_item_bulk_update_location_bulkUpdateLocation } from "~backend/item/bulk_update_location";
import { confirmLocation as api_item_confirm_location_confirmLocation } from "~backend/item/confirm_location";
import { create as api_item_create_create } from "~backend/item/create";
import { deleteItem as api_item_delete_deleteItem } from "~backend/item/delete";
import { deleteReceipt as api_item_delete_receipt_deleteReceipt } from "~backend/item/delete_receipt";
import { detectBarcode as api_item_detect_barcode_detectBarcode } from "~backend/item/detect_barcode";
import { expiring as api_item_expiring_expiring } from "~backend/item/expiring";
import { extractReceiptData as api_item_extract_receipt_data_extractReceiptData } from "~backend/item/extract_receipt_data";
import { favorites as api_item_favorites_favorites } from "~backend/item/favorites";
import { get as api_item_get_get } from "~backend/item/get";
import { getConsumptionHistory as api_item_get_consumption_history_getConsumptionHistory } from "~backend/item/get_consumption_history";
import { listByContainer as api_item_list_by_container_listByContainer } from "~backend/item/list_by_container";
import { listByLocation as api_item_list_by_location_listByLocation } from "~backend/item/list_by_location";
import { listByPlacedStatus as api_item_list_by_placed_status_listByPlacedStatus } from "~backend/item/list_by_placed_status";
import { listReceipts as api_item_list_receipts_listReceipts } from "~backend/item/list_receipts";
import { lowStock as api_item_low_stock_lowStock } from "~backend/item/low_stock";
import { needsConfirmation as api_item_needs_confirmation_needsConfirmation } from "~backend/item/needs_confirmation";
import { recent as api_item_recent_recent } from "~backend/item/recent";
import { recordConsumption as api_item_record_consumption_recordConsumption } from "~backend/item/record_consumption";
import { search as api_item_search_search } from "~backend/item/search";
import { getCategoryStatsByLocation as api_item_stats_getCategoryStatsByLocation } from "~backend/item/stats";
import { toggleFavorite as api_item_toggle_favorite_toggleFavorite } from "~backend/item/toggle_favorite";
import { update as api_item_update_update } from "~backend/item/update";
import { updateQuantity as api_item_update_quantity_updateQuantity } from "~backend/item/update_quantity";
import { uploadPhoto as api_item_upload_photo_uploadPhoto } from "~backend/item/upload_photo";
import { uploadReceipt as api_item_upload_receipt_uploadReceipt } from "~backend/item/upload_receipt";

export namespace item {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.addReceipt = this.addReceipt.bind(this)
            this.analyzeBookshelf = this.analyzeBookshelf.bind(this)
            this.analyzeShelf = this.analyzeShelf.bind(this)
            this.analyzeShelfOcr = this.analyzeShelfOcr.bind(this)
            this.batchCreate = this.batchCreate.bind(this)
            this.batchListByContainers = this.batchListByContainers.bind(this)
            this.batchListByLocations = this.batchListByLocations.bind(this)
            this.bulkAddTags = this.bulkAddTags.bind(this)
            this.bulkConfirmLocation = this.bulkConfirmLocation.bind(this)
            this.bulkDelete = this.bulkDelete.bind(this)
            this.bulkUpdateLocation = this.bulkUpdateLocation.bind(this)
            this.confirmLocation = this.confirmLocation.bind(this)
            this.create = this.create.bind(this)
            this.deleteItem = this.deleteItem.bind(this)
            this.deleteReceipt = this.deleteReceipt.bind(this)
            this.detectBarcode = this.detectBarcode.bind(this)
            this.expiring = this.expiring.bind(this)
            this.extractReceiptData = this.extractReceiptData.bind(this)
            this.favorites = this.favorites.bind(this)
            this.get = this.get.bind(this)
            this.getCategoryStatsByLocation = this.getCategoryStatsByLocation.bind(this)
            this.getConsumptionHistory = this.getConsumptionHistory.bind(this)
            this.listByContainer = this.listByContainer.bind(this)
            this.listByLocation = this.listByLocation.bind(this)
            this.listByPlacedStatus = this.listByPlacedStatus.bind(this)
            this.listReceipts = this.listReceipts.bind(this)
            this.lookupBarcode = this.lookupBarcode.bind(this)
            this.lowStock = this.lowStock.bind(this)
            this.needsConfirmation = this.needsConfirmation.bind(this)
            this.recent = this.recent.bind(this)
            this.recordConsumption = this.recordConsumption.bind(this)
            this.search = this.search.bind(this)
            this.toggleFavorite = this.toggleFavorite.bind(this)
            this.update = this.update.bind(this)
            this.updateQuantity = this.updateQuantity.bind(this)
            this.uploadPhoto = this.uploadPhoto.bind(this)
            this.uploadReceipt = this.uploadReceipt.bind(this)
        }

        public async addReceipt(params: RequestType<typeof api_item_add_receipt_addReceipt>): Promise<ResponseType<typeof api_item_add_receipt_addReceipt>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/item/add-receipt`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_item_add_receipt_addReceipt>
        }

        public async analyzeBookshelf(params: RequestType<typeof api_item_analyze_bookshelf_analyzeBookshelf>): Promise<ResponseType<typeof api_item_analyze_bookshelf_analyzeBookshelf>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/items/analyze-bookshelf`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_item_analyze_bookshelf_analyzeBookshelf>
        }

        public async analyzeShelf(params: RequestType<typeof api_item_analyze_shelf_analyzeShelf>): Promise<ResponseType<typeof api_item_analyze_shelf_analyzeShelf>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/items/analyze-shelf`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_item_analyze_shelf_analyzeShelf>
        }

        public async analyzeShelfOcr(params: RequestType<typeof api_item_analyze_shelf_ocr_analyzeShelfOcr>): Promise<ResponseType<typeof api_item_analyze_shelf_ocr_analyzeShelfOcr>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/item/analyze-shelf-ocr`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_item_analyze_shelf_ocr_analyzeShelfOcr>
        }

        public async batchCreate(params: RequestType<typeof api_item_batch_create_batchCreate>): Promise<ResponseType<typeof api_item_batch_create_batchCreate>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/items/batch-create`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_item_batch_create_batchCreate>
        }

        public async batchListByContainers(params: RequestType<typeof api_item_batch_list_by_containers_batchListByContainers>): Promise<ResponseType<typeof api_item_batch_list_by_containers_batchListByContainers>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/items/batch/containers`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_item_batch_list_by_containers_batchListByContainers>
        }

        public async batchListByLocations(params: RequestType<typeof api_item_batch_list_by_locations_batchListByLocations>): Promise<ResponseType<typeof api_item_batch_list_by_locations_batchListByLocations>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/items/batch/locations`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_item_batch_list_by_locations_batchListByLocations>
        }

        public async bulkAddTags(params: RequestType<typeof api_item_bulk_add_tags_bulkAddTags>): Promise<ResponseType<typeof api_item_bulk_add_tags_bulkAddTags>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/items/bulk-add-tags`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_item_bulk_add_tags_bulkAddTags>
        }

        public async bulkConfirmLocation(params: RequestType<typeof api_item_bulk_confirm_location_bulkConfirmLocation>): Promise<ResponseType<typeof api_item_bulk_confirm_location_bulkConfirmLocation>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/items/bulk-confirm-location`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_item_bulk_confirm_location_bulkConfirmLocation>
        }

        public async bulkDelete(params: RequestType<typeof api_item_bulk_delete_bulkDelete>): Promise<void> {
            await this.baseClient.callTypedAPI(`/items/bulk-delete`, {method: "POST", body: JSON.stringify(params)})
        }

        public async bulkUpdateLocation(params: RequestType<typeof api_item_bulk_update_location_bulkUpdateLocation>): Promise<ResponseType<typeof api_item_bulk_update_location_bulkUpdateLocation>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/items/bulk-update-location`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_item_bulk_update_location_bulkUpdateLocation>
        }

        public async confirmLocation(params: { id: number }): Promise<ResponseType<typeof api_item_confirm_location_confirmLocation>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/items/${encodeURIComponent(params.id)}/confirm`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_item_confirm_location_confirmLocation>
        }

        /**
         * Creates a new item in the inventory.
         */
        public async create(params: RequestType<typeof api_item_create_create>): Promise<ResponseType<typeof api_item_create_create>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/items`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_item_create_create>
        }

        /**
         * Deletes an item from the inventory.
         */
        public async deleteItem(params: { id: number }): Promise<void> {
            await this.baseClient.callTypedAPI(`/items/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
        }

        public async deleteReceipt(params: { receiptId: number }): Promise<ResponseType<typeof api_item_delete_receipt_deleteReceipt>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/item/receipt/${encodeURIComponent(params.receiptId)}`, {method: "DELETE", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_item_delete_receipt_deleteReceipt>
        }

        /**
         * Fast barcode-only detection endpoint with timeout
         */
        public async detectBarcode(params: RequestType<typeof api_item_detect_barcode_detectBarcode>): Promise<ResponseType<typeof api_item_detect_barcode_detectBarcode>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/item/detect-barcode`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_item_detect_barcode_detectBarcode>
        }

        public async expiring(params: RequestType<typeof api_item_expiring_expiring>): Promise<ResponseType<typeof api_item_expiring_expiring>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:  params.limit === undefined ? undefined : String(params.limit),
                offset: params.offset === undefined ? undefined : String(params.offset),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/items/expiring`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_item_expiring_expiring>
        }

        public async extractReceiptData(params: RequestType<typeof api_item_extract_receipt_data_extractReceiptData>): Promise<ResponseType<typeof api_item_extract_receipt_data_extractReceiptData>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/item/extract-receipt-data`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_item_extract_receipt_data_extractReceiptData>
        }

        /**
         * Retrieves all favorite items.
         */
        public async favorites(params: RequestType<typeof api_item_favorites_favorites>): Promise<ResponseType<typeof api_item_favorites_favorites>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:  params.limit === undefined ? undefined : String(params.limit),
                offset: params.offset === undefined ? undefined : String(params.offset),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/items/favorites`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_item_favorites_favorites>
        }

        /**
         * Retrieves a single item by ID.
         */
        public async get(params: { id: number }): Promise<ResponseType<typeof api_item_get_get>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/items/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_item_get_get>
        }

        public async getCategoryStatsByLocation(params: { locationId: string }): Promise<ResponseType<typeof api_item_stats_getCategoryStatsByLocation>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/items/stats/${encodeURIComponent(params.locationId)}/categories`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_item_stats_getCategoryStatsByLocation>
        }

        public async getConsumptionHistory(params: { itemId: number }): Promise<ResponseType<typeof api_item_get_consumption_history_getConsumptionHistory>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/items/${encodeURIComponent(params.itemId)}/consumption-history`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_item_get_consumption_history_getConsumptionHistory>
        }

        public async listByContainer(params: { containerId: string }): Promise<ResponseType<typeof api_item_list_by_container_listByContainer>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/items/container/${encodeURIComponent(params.containerId)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_item_list_by_container_listByContainer>
        }

        public async listByLocation(params: { locationId: string }): Promise<ResponseType<typeof api_item_list_by_location_listByLocation>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/items/location/${encodeURIComponent(params.locationId)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_item_list_by_location_listByLocation>
        }

        public async listByPlacedStatus(params: RequestType<typeof api_item_list_by_placed_status_listByPlacedStatus>): Promise<ResponseType<typeof api_item_list_by_placed_status_listByPlacedStatus>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:  params.limit === undefined ? undefined : String(params.limit),
                offset: params.offset === undefined ? undefined : String(params.offset),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/items/placed/${encodeURIComponent(params.status)}`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_item_list_by_placed_status_listByPlacedStatus>
        }

        public async listReceipts(params: { itemId: number }): Promise<ResponseType<typeof api_item_list_receipts_listReceipts>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/item/${encodeURIComponent(params.itemId)}/receipts`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_item_list_receipts_listReceipts>
        }

        public async lookupBarcode(params: { upc: string }): Promise<ResponseType<typeof api_item_barcode_lookupBarcode>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/items/barcode/${encodeURIComponent(params.upc)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_item_barcode_lookupBarcode>
        }

        public async lowStock(params: RequestType<typeof api_item_low_stock_lowStock>): Promise<ResponseType<typeof api_item_low_stock_lowStock>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:  params.limit === undefined ? undefined : String(params.limit),
                offset: params.offset === undefined ? undefined : String(params.offset),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/items/low-stock`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_item_low_stock_lowStock>
        }

        public async needsConfirmation(params: RequestType<typeof api_item_needs_confirmation_needsConfirmation>): Promise<ResponseType<typeof api_item_needs_confirmation_needsConfirmation>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:  params.limit === undefined ? undefined : String(params.limit),
                offset: params.offset === undefined ? undefined : String(params.offset),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/items/needs-confirmation`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_item_needs_confirmation_needsConfirmation>
        }

        /**
         * Retrieves the 10 most recently added items.
         */
        public async recent(params: RequestType<typeof api_item_recent_recent>): Promise<ResponseType<typeof api_item_recent_recent>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:  params.limit === undefined ? undefined : String(params.limit),
                offset: params.offset === undefined ? undefined : String(params.offset),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/items/recent`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_item_recent_recent>
        }

        public async recordConsumption(params: RequestType<typeof api_item_record_consumption_recordConsumption>): Promise<ResponseType<typeof api_item_record_consumption_recordConsumption>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                consumedQuantity: params.consumedQuantity,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/items/${encodeURIComponent(params.itemId)}/consume`, {method: "POST", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_item_record_consumption_recordConsumption>
        }

        /**
         * Searches items by name, description, or tags.
         */
        public async search(params: RequestType<typeof api_item_search_search>): Promise<ResponseType<typeof api_item_search_search>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:  params.limit === undefined ? undefined : String(params.limit),
                offset: params.offset === undefined ? undefined : String(params.offset),
                query:  params.query,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/items/search`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_item_search_search>
        }

        /**
         * Toggles an item's favorite status.
         */
        public async toggleFavorite(params: { id: number }): Promise<ResponseType<typeof api_item_toggle_favorite_toggleFavorite>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/items/${encodeURIComponent(params.id)}/favorite`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_item_toggle_favorite_toggleFavorite>
        }

        /**
         * Updates an item's properties.
         */
        public async update(params: RequestType<typeof api_item_update_update>): Promise<ResponseType<typeof api_item_update_update>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                consumption:    params.consumption,
                containerId:    params.containerId,
                description:    params.description,
                expirationDate: params.expirationDate,
                isFavorite:     params.isFavorite,
                locationId:     params.locationId,
                name:           params.name,
                notes:          params.notes,
                photoUrl:       params.photoUrl,
                quantity:       params.quantity,
                tags:           params.tags,
                thumbnailUrl:   params.thumbnailUrl,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/items/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_item_update_update>
        }

        /**
         * Updates just the quantity of an item quickly
         */
        public async updateQuantity(params: RequestType<typeof api_item_update_quantity_updateQuantity>): Promise<ResponseType<typeof api_item_update_quantity_updateQuantity>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                quantity: params.quantity,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/items/${encodeURIComponent(params.id)}/quantity`, {method: "PATCH", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_item_update_quantity_updateQuantity>
        }

        public async uploadPhoto(params: RequestType<typeof api_item_upload_photo_uploadPhoto>): Promise<ResponseType<typeof api_item_upload_photo_uploadPhoto>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/items/upload-photo`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_item_upload_photo_uploadPhoto>
        }

        public async uploadReceipt(params: RequestType<typeof api_item_upload_receipt_uploadReceipt>): Promise<ResponseType<typeof api_item_upload_receipt_uploadReceipt>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/item/upload-receipt`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_item_upload_receipt_uploadReceipt>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { create as api_location_create_create } from "~backend/location/create";
import { deleteLocation as api_location_delete_deleteLocation } from "~backend/location/delete";
import { list as api_location_list_list } from "~backend/location/list";
import { update as api_location_update_update } from "~backend/location/update";

export namespace location {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.deleteLocation = this.deleteLocation.bind(this)
            this.list = this.list.bind(this)
            this.update = this.update.bind(this)
        }

        /**
         * Creates a new location for organizing items.
         */
        public async create(params: RequestType<typeof api_location_create_create>): Promise<ResponseType<typeof api_location_create_create>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/locations`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_location_create_create>
        }

        /**
         * Deletes a location and unlinks associated items.
         */
        public async deleteLocation(params: { id: number }): Promise<void> {
            await this.baseClient.callTypedAPI(`/locations/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
        }

        /**
         * Retrieves all locations for the user.
         */
        public async list(): Promise<ResponseType<typeof api_location_list_list>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/locations`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_location_list_list>
        }

        /**
         * Updates a location's name.
         */
        public async update(params: RequestType<typeof api_location_update_update>): Promise<ResponseType<typeof api_location_update_update>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                name: params.name,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/locations/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_location_update_update>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { add as api_shopping_add_add } from "~backend/shopping/add";
import { deleteItem as api_shopping_delete_deleteItem } from "~backend/shopping/delete";
import { list as api_shopping_list_list } from "~backend/shopping/list";
import { lowStockItems as api_shopping_low_stock_items_lowStockItems } from "~backend/shopping/low_stock_items";
import { update as api_shopping_update_update } from "~backend/shopping/update";

export namespace shopping {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.add = this.add.bind(this)
            this.deleteItem = this.deleteItem.bind(this)
            this.list = this.list.bind(this)
            this.lowStockItems = this.lowStockItems.bind(this)
            this.update = this.update.bind(this)
        }

        public async add(params: RequestType<typeof api_shopping_add_add>): Promise<ResponseType<typeof api_shopping_add_add>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/shopping`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_shopping_add_add>
        }

        public async deleteItem(params: { id: number }): Promise<void> {
            await this.baseClient.callTypedAPI(`/shopping/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
        }

        public async list(): Promise<ResponseType<typeof api_shopping_list_list>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/shopping`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_shopping_list_list>
        }

        public async lowStockItems(): Promise<ResponseType<typeof api_shopping_low_stock_items_lowStockItems>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/shopping/low-stock`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_shopping_low_stock_items_lowStockItems>
        }

        public async update(params: RequestType<typeof api_shopping_update_update>): Promise<ResponseType<typeof api_shopping_update_update>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                isPurchased: params.isPurchased,
                quantity:    params.quantity,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/shopping/${encodeURIComponent(params.id)}`, {method: "PATCH", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_shopping_update_update>
        }
    }
}


type PickMethods<Type> = Omit<CallParameters, "method"> & { method?: Type };

// Helper type to omit all fields that are cookies.
type OmitCookie<T> = {
  [K in keyof T as T[K] extends CookieWithOptions<any> ? never : K]: T[K];
};

type RequestType<Type extends (...args: any[]) => any> =
  Parameters<Type> extends [infer H, ...any[]]
    ? OmitCookie<H>
    : void;

type ResponseType<Type extends (...args: any[]) => any> = OmitCookie<Awaited<ReturnType<Type>>>;

function dateReviver(key: string, value: any): any {
  if (
    typeof value === "string" &&
    value.length >= 10 &&
    value.charCodeAt(0) >= 48 && // '0'
    value.charCodeAt(0) <= 57 // '9'
  ) {
    const parsedDate = new Date(value);
    if (!isNaN(parsedDate.getTime())) {
      return parsedDate;
    }
  }
  return value;
}


function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ?  parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}

import {
  StreamInOutHandlerFn,
  StreamInHandlerFn,
  StreamOutHandlerFn,
} from "encore.dev/api";

type StreamRequest<Type> = Type extends
  | StreamInOutHandlerFn<any, infer Req, any>
  | StreamInHandlerFn<any, infer Req, any>
  | StreamOutHandlerFn<any, any>
  ? Req
  : never;

type StreamResponse<Type> = Type extends
  | StreamInOutHandlerFn<any, any, infer Resp>
  | StreamInHandlerFn<any, any, infer Resp>
  | StreamOutHandlerFn<any, infer Resp>
  ? Resp
  : never;


function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
      .replaceAll("=", "")
      .replaceAll("+", "-")
      .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data, dateReviver))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}

// AuthDataGenerator is a function that returns a new instance of the authentication data required by this API
export type AuthDataGenerator = () =>
  | RequestType<typeof auth_auth>
  | Promise<RequestType<typeof auth_auth> | undefined>
  | undefined;

// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
    readonly authGenerator?: AuthDataGenerator

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (!BROWSER) {
            this.headers["User-Agent"] = "whereisit-inventory-app-9xhi-Generated-TS-Client (Encore/v1.53.0)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }

        // Setup an authentication data generator using the auth data token option
        if (options.auth !== undefined) {
            const auth = options.auth
            if (typeof auth === "function") {
                this.authGenerator = auth
            } else {
                this.authGenerator = () => auth
            }
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        let authData: RequestType<typeof auth_auth> | undefined;

        // If authorization data generator is present, call it and add the returned data to the request
        if (this.authGenerator) {
            const mayBePromise = this.authGenerator();
            if (mayBePromise instanceof Promise) {
                authData = await mayBePromise;
            } else {
                authData = mayBePromise;
            }
        }

        if (authData) {
            const data: CallParameters = {};

            data.headers = makeRecord<string, string>({
                authorization: authData.authorization,
            });

            return data;
        }

        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(path: string, params?: CallParameters): Promise<Response> {
        return this.callAPI(path, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(path: string, params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
        }

        // Merge our headers with any predefined headers
        init.headers = {...this.headers, ...init.headers, ...headers}

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                init.headers = {...init.headers, ...authData.headers};
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL+path+queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof(err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof(err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value:        'APIError',
            enumerable:   false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}

export default new Client(import.meta.env.VITE_CLIENT_TARGET, { requestInit: { credentials: "include" } });
