// Code generated by the Encore v1.51.11 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:4000"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-whereisit-inventory-app-9xhi.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === "object" && ("window" in globalThis);

/**
 * Client is an API client for the whereisit-inventory-app-9xhi Encore application.
 */
export default class Client {
    public readonly container: container.ServiceClient
    public readonly folder: folder.ServiceClient
    public readonly frontend: frontend.ServiceClient
    public readonly household: household.ServiceClient
    public readonly image: image.ServiceClient
    public readonly item: item.ServiceClient
    public readonly location: location.ServiceClient
    public readonly shopping: shopping.ServiceClient
    private readonly options: ClientOptions
    private readonly target: string


    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions) {
        this.target = target
        this.options = options ?? {}
        const base = new BaseClient(this.target, this.options)
        this.container = new container.ServiceClient(base)
        this.folder = new folder.ServiceClient(base)
        this.frontend = new frontend.ServiceClient(base)
        this.household = new household.ServiceClient(base)
        this.image = new image.ServiceClient(base)
        this.item = new item.ServiceClient(base)
        this.location = new location.ServiceClient(base)
        this.shopping = new shopping.ServiceClient(base)
    }

    /**
     * Creates a new Encore client with the given client options set.
     *
     * @param options Client options to set. They are merged with existing options.
     **/
    public with(options: ClientOptions): Client {
        return new Client(this.target, {
            ...this.options,
            ...options,
        })
    }
}

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    /**
     * Allows you to set the authentication data to be used for each
     * request either by passing in a static object or by passing in
     * a function which returns a new object for each request.
     */
    auth?: auth.AuthParams | AuthDataGenerator
}

export namespace auth {
    export interface AuthParams {
        authorization?: string
    }
}

export namespace container {
    export interface Container {
        id: number
        name: string
        locationId: number | null
        photoUrl: string | null
    }

    export interface CreateContainerRequest {
        name: string
        locationId: number
    }

    export interface ListAllResponse {
        containers: {
            id: number
            name: string
            locationId: number | null
            photoUrl: string | null
            locationName: string | null
        }[]
    }

    export interface ListByLocationResponse {
        containers: Container[]
    }

    export interface UpdateContainerRequest {
        name?: string
        locationId?: number
        photoUrl?: string
    }

    export interface UpdateContainerResponse {
        container: Container
    }

    export interface UploadPhotoRequest {
        filename: string
        contentType: string
        data: string
    }

    export interface UploadPhotoResponse {
        url: string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.deleteContainer = this.deleteContainer.bind(this)
            this.list = this.list.bind(this)
            this.listByLocation = this.listByLocation.bind(this)
            this.update = this.update.bind(this)
            this.uploadPhoto = this.uploadPhoto.bind(this)
        }

        public async create(params: CreateContainerRequest): Promise<Container> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/containers`, JSON.stringify(params))
            return await resp.json() as Container
        }

        public async deleteContainer(id: string): Promise<void> {
            await this.baseClient.callTypedAPI("DELETE", `/containers/${encodeURIComponent(id)}`)
        }

        public async list(): Promise<ListAllResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/containers`)
            return await resp.json() as ListAllResponse
        }

        public async listByLocation(locationId: string): Promise<ListByLocationResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/locations/${encodeURIComponent(locationId)}/containers`)
            return await resp.json() as ListByLocationResponse
        }

        public async update(id: string, params: UpdateContainerRequest): Promise<UpdateContainerResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PUT", `/containers/${encodeURIComponent(id)}`, JSON.stringify(params))
            return await resp.json() as UpdateContainerResponse
        }

        public async uploadPhoto(params: UploadPhotoRequest): Promise<UploadPhotoResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/containers/upload-photo`, JSON.stringify(params))
            return await resp.json() as UploadPhotoResponse
        }
    }
}

export namespace folder {
    export interface CreateFolderRequest {
        name: string
    }

    export interface Folder {
        id: string
        name: string
        createdAt: string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
        }

        public async create(params: CreateFolderRequest): Promise<Folder> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/folders`, JSON.stringify(params))
            return await resp.json() as Folder
        }
    }
}

export namespace frontend {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.assets = this.assets.bind(this)
        }

        public async assets(path: string[]): Promise<void> {
            await this.baseClient.callTypedAPI("HEAD", `/frontend/${path.map(encodeURIComponent).join("/")}`)
        }
    }
}

export namespace household {
    export interface AcceptInvitationRequest {
        "invitation_id": number
    }

    export interface AcceptInvitationResponse {
        success: boolean
        "household_id": number
    }

    export interface CancelInvitationRequest {
        "invitation_id": number
    }

    export interface CreateHouseholdRequest {
        name: string
    }

    export interface GetHouseholdByIdResponse {
        id: number
        name: string
        "created_at": string
    }

    export interface GetHouseholdResponse {
        household: Household | null
        "current_user_id": string
    }

    export interface GetInvitationsResponse {
        invitations: HouseholdInvitation[]
    }

    export interface GetMembersResponse {
        members: HouseholdMember[]
    }

    export interface GetPendingInvitationsResponse {
        invitations: HouseholdInvitation[]
    }

    export interface Household {
        id: number
        name: string
        "owner_id": string | null
        "created_at": string
    }

    export interface HouseholdInvitation {
        id: number
        "household_id": number
        "invited_email": string
        status: string
        "created_at": string
    }

    export interface HouseholdMember {
        id: string
        "created_at": string
        "is_owner": boolean
    }

    export interface InviteRequest {
        "invited_email": string
    }

    export interface InviteResponse {
        id: number
        "invited_email": string
        status: string
    }

    export interface RemoveMemberRequest {
        "user_id": string
    }

    export interface RenameHouseholdRequest {
        name: string
    }

    export interface RenameHouseholdResponse {
        success: boolean
    }

    export interface ResendInvitationRequest {
        "invitation_id": number
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.acceptInvitation = this.acceptInvitation.bind(this)
            this.cancelInvitation = this.cancelInvitation.bind(this)
            this.create = this.create.bind(this)
            this.get = this.get.bind(this)
            this.getHouseholdById = this.getHouseholdById.bind(this)
            this.getInvitations = this.getInvitations.bind(this)
            this.getMembers = this.getMembers.bind(this)
            this.getPendingInvitations = this.getPendingInvitations.bind(this)
            this.invite = this.invite.bind(this)
            this.leave = this.leave.bind(this)
            this.removeMember = this.removeMember.bind(this)
            this.rename = this.rename.bind(this)
            this.resendInvitation = this.resendInvitation.bind(this)
        }

        public async acceptInvitation(params: AcceptInvitationRequest): Promise<AcceptInvitationResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/household/accept-invitation`, JSON.stringify(params))
            return await resp.json() as AcceptInvitationResponse
        }

        public async cancelInvitation(params: CancelInvitationRequest): Promise<void> {
            await this.baseClient.callTypedAPI("POST", `/household/cancel-invitation`, JSON.stringify(params))
        }

        public async create(params: CreateHouseholdRequest): Promise<Household> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/household`, JSON.stringify(params))
            return await resp.json() as Household
        }

        public async get(): Promise<GetHouseholdResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/household`)
            return await resp.json() as GetHouseholdResponse
        }

        public async getHouseholdById(household_id: number): Promise<GetHouseholdByIdResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/household/${encodeURIComponent(household_id)}`)
            return await resp.json() as GetHouseholdByIdResponse
        }

        public async getInvitations(): Promise<GetInvitationsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/household/invitations`)
            return await resp.json() as GetInvitationsResponse
        }

        public async getMembers(): Promise<GetMembersResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/household/members`)
            return await resp.json() as GetMembersResponse
        }

        public async getPendingInvitations(): Promise<GetPendingInvitationsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/household/pending-invitations`)
            return await resp.json() as GetPendingInvitationsResponse
        }

        public async invite(params: InviteRequest): Promise<InviteResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/household/invite`, JSON.stringify(params))
            return await resp.json() as InviteResponse
        }

        public async leave(): Promise<void> {
            await this.baseClient.callTypedAPI("POST", `/household/leave`)
        }

        public async removeMember(params: RemoveMemberRequest): Promise<void> {
            await this.baseClient.callTypedAPI("POST", `/household/remove-member`, JSON.stringify(params))
        }

        public async rename(params: RenameHouseholdRequest): Promise<RenameHouseholdResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PUT", `/household/rename`, JSON.stringify(params))
            return await resp.json() as RenameHouseholdResponse
        }

        public async resendInvitation(params: ResendInvitationRequest): Promise<void> {
            await this.baseClient.callTypedAPI("POST", `/household/resend-invitation`, JSON.stringify(params))
        }
    }
}

export namespace image {
    export interface AnalyzeRequest {
        imageData: string
        mimeType: string
    }

    export interface AnalyzeResponse {
        result: string
    }

    export interface GetUploadUrlRequest {
        filename: string
        contentType: string
    }

    export interface GetUploadUrlResponse {
        uploadUrl: string
        fileUrl: string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.analyze = this.analyze.bind(this)
            this.getUploadUrl = this.getUploadUrl.bind(this)
        }

        public async analyze(params: AnalyzeRequest): Promise<AnalyzeResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/analyze`, JSON.stringify(params))
            return await resp.json() as AnalyzeResponse
        }

        public async getUploadUrl(params: GetUploadUrlRequest): Promise<GetUploadUrlResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/image/upload-url`, JSON.stringify(params))
            return await resp.json() as GetUploadUrlResponse
        }
    }
}

export namespace item {
    export interface AddReceiptRequest {
        itemId: number
        receiptUrl: string
        thumbnailUrl: string
        receiptType: "purchase" | "warranty" | "repair" | "upgrade"
        description?: string
        extractedDate?: string
        extractedPrice?: number
        extractedStore?: string
    }

    export interface AnalyzeBookshelfRequest {
        imageUrls: string[]
    }

    export interface AnalyzeBookshelfResponse {
        books: BookAnalysis[]
    }

    export interface AnalyzeShelfRequest {
        imageUrls: string[]
    }

    export interface AnalyzeShelfResponse {
        items: AnalyzedItem[]
    }

    export interface AnalyzedItem {
        name: string
        description: string
        brand: string | null
        color: string | null
        size: string | null
        quantity: number
        expirationDate: string | null
        category: string | null
        notes: string | null
    }

    export interface BatchCreateRequest {
        items: BatchItem[]
        locationId?: number
    }

    export interface BatchCreateResponse {
        items: Item[]
    }

    export interface BatchItem {
        name: string
        description: string
        brand?: string | null
        color?: string | null
        size?: string | null
        quantity?: number | null
        expirationDate?: string | null
        category?: string | null
        notes?: string | null
        containerId?: number | null
    }

    export interface BatchListByContainersRequest {
        containerIds: number[]
    }

    export interface BatchListByContainersResponse {
        itemsByContainer: { [key: number]: Item[] }
    }

    export interface BatchListByLocationsRequest {
        locationIds: number[]
    }

    export interface BatchListByLocationsResponse {
        itemsByLocation: { [key: number]: Item[] }
    }

    export interface BookAnalysis {
        "guessed_title": string
        "guessed_author": string
        "visual_signature": string
        "shelf_location": string
        "search_query": string
    }

    export interface BulkAddTagsRequest {
        itemIds: number[]
        tags: string[]
    }

    export interface BulkAddTagsResponse {
        count: number
    }

    export interface BulkConfirmLocationRequest {
        itemIds: number[]
    }

    export interface BulkConfirmLocationResponse {
        count: number
    }

    export interface BulkDeleteRequest {
        itemIds: number[]
    }

    export interface BulkUpdateLocationRequest {
        itemIds: number[]
        locationId: number
        containerId?: number | null
    }

    export interface BulkUpdateLocationResponse {
        count: number
    }

    export interface CategoryStat {
        category: string
        count: number
    }

    export interface ConfirmLocationResponse {
        success: boolean
        lastConfirmedAt: string
    }

    export interface ConsumptionEntry {
        id: number
        itemId: number
        quantityRemaining: number
        consumedQuantity: number
        recordedAt: string
    }

    export interface CreateItemRequest {
        name: string
        locationId?: number
        containerId?: number | null
        description?: string
        photoUrl?: string
        thumbnailUrl?: string
        brand?: string | null
        color?: string | null
        size?: string | null
        quantity?: number | null
        expirationDate?: string | null
        category?: string | null
        notes?: string | null
        tags?: string[]
    }

    export interface DeleteReceiptResponse {
        success: boolean
    }

    export interface ExpiringItemsRequest {
        limit?: number
        offset?: number
    }

    export interface ExpiringItemsResponse {
        items: Item[]
        total: number
        hasMore: boolean
    }

    export interface ExtractReceiptDataRequest {
        imageUrl: string
    }

    export interface ExtractedReceiptData {
        extractedDate: string | null
        extractedPrice: number | null
        extractedStore: string | null
        rawText: string
    }

    export interface FavoriteItemsRequest {
        limit?: number
        offset?: number
    }

    export interface FavoriteItemsResponse {
        items: Item[]
        total: number
        hasMore: boolean
    }

    export interface GetCategoryStatsByLocationResponse {
        stats: CategoryStat[]
    }

    export interface GetConsumptionHistoryResponse {
        history: ConsumptionEntry[]
        initialQuantity: number
    }

    export interface Item {
        id: number
        userId: string
        locationId?: number
        containerId?: number
        locationName?: string
        containerName?: string
        name: string
        description?: string
        photoUrl?: string
        thumbnailUrl?: string
        brand?: string
        color?: string
        size?: string
        quantity: number
        consumption: number
        expirationDate?: string
        category?: string
        notes?: string
        tags: string[]
        isFavorite: boolean
        createdAt: string
        lastConfirmedAt?: string
    }

    export interface ItemReceipt {
        id: number
        itemId: number
        receiptUrl: string
        thumbnailUrl: string
        receiptType: string
        description: string | null
        extractedDate: string | null
        extractedPrice: number | null
        extractedStore: string | null
        uploadedAt: string
        uploadedBy: string
    }

    export interface ListByPlacedStatusRequest {
        limit?: number
        offset?: number
    }

    export interface ListByPlacedStatusResponse {
        items: Item[]
        total: number
        hasMore: boolean
    }

    export interface ListItemsByContainerResponse {
        items: Item[]
    }

    export interface ListItemsByLocationResponse {
        items: Item[]
    }

    export interface ListReceiptsResponse {
        receipts: ItemReceipt[]
    }

    export interface LookupBarcodeResponse {
        name: string
        description?: string
        brand?: string
        color?: string
        size?: string
    }

    export interface LowStockItem {
        id: number
        name: string
        description: string | null
        photoUrl: string | null
        thumbnailUrl: string | null
        quantity: number
        locationId: number | null
        locationName: string | null
        tags: string[]
        expirationDate: string | null
        isFavorite: boolean
        reorderPoint: number
        averageDailyConsumption: number
        daysUntilEmpty: number | null
    }

    export interface LowStockRequest {
        limit?: number
        offset?: number
    }

    export interface LowStockResponse {
        items: LowStockItem[]
        total: number
        hasMore: boolean
    }

    export interface NeedsConfirmationRequest {
        limit?: number
        offset?: number
    }

    export interface NeedsConfirmationResponse {
        items: Item[]
        total: number
        hasMore: boolean
    }

    export interface RecentItemsRequest {
        limit?: number
        offset?: number
    }

    export interface RecentItemsResponse {
        items: Item[]
        total: number
        hasMore: boolean
    }

    export interface RecordConsumptionRequest {
        consumedQuantity: number
    }

    export interface RecordConsumptionResponse {
        success: boolean
        newQuantity: number
    }

    export interface SearchItemsRequest {
        query: string
        limit?: number
        offset?: number
    }

    export interface SearchItemsResponse {
        items: Item[]
        total: number
        hasMore: boolean
    }

    export interface UpdateItemRequest {
        name?: string
        locationId?: number | null
        containerId?: number | null
        description?: string
        photoUrl?: string
        thumbnailUrl?: string
        quantity?: number
        consumption?: number
        expirationDate?: string
        notes?: string
        tags?: string[]
        isFavorite?: boolean
    }

    export interface UpdateQuantityRequest {
        quantity: number
    }

    export interface UpdateQuantityResponse {
        success: boolean
        newQuantity: number
    }

    export interface UploadPhotoRequest {
        filename: string
        contentType: string
        data: string
    }

    export interface UploadPhotoResponse {
        url: string
        thumbnailUrl: string
    }

    export interface UploadReceiptRequest {
        base64Image: string
    }

    export interface UploadReceiptResponse {
        receiptUrl: string
        thumbnailUrl: string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.addReceipt = this.addReceipt.bind(this)
            this.analyzeBookshelf = this.analyzeBookshelf.bind(this)
            this.analyzeShelf = this.analyzeShelf.bind(this)
            this.batchCreate = this.batchCreate.bind(this)
            this.batchListByContainers = this.batchListByContainers.bind(this)
            this.batchListByLocations = this.batchListByLocations.bind(this)
            this.bulkAddTags = this.bulkAddTags.bind(this)
            this.bulkConfirmLocation = this.bulkConfirmLocation.bind(this)
            this.bulkDelete = this.bulkDelete.bind(this)
            this.bulkUpdateLocation = this.bulkUpdateLocation.bind(this)
            this.confirmLocation = this.confirmLocation.bind(this)
            this.create = this.create.bind(this)
            this.deleteItem = this.deleteItem.bind(this)
            this.deleteReceipt = this.deleteReceipt.bind(this)
            this.expiring = this.expiring.bind(this)
            this.extractReceiptData = this.extractReceiptData.bind(this)
            this.favorites = this.favorites.bind(this)
            this.get = this.get.bind(this)
            this.getCategoryStatsByLocation = this.getCategoryStatsByLocation.bind(this)
            this.getConsumptionHistory = this.getConsumptionHistory.bind(this)
            this.listByContainer = this.listByContainer.bind(this)
            this.listByLocation = this.listByLocation.bind(this)
            this.listByPlacedStatus = this.listByPlacedStatus.bind(this)
            this.listReceipts = this.listReceipts.bind(this)
            this.lookupBarcode = this.lookupBarcode.bind(this)
            this.lowStock = this.lowStock.bind(this)
            this.needsConfirmation = this.needsConfirmation.bind(this)
            this.recent = this.recent.bind(this)
            this.recordConsumption = this.recordConsumption.bind(this)
            this.search = this.search.bind(this)
            this.toggleFavorite = this.toggleFavorite.bind(this)
            this.update = this.update.bind(this)
            this.updateQuantity = this.updateQuantity.bind(this)
            this.uploadPhoto = this.uploadPhoto.bind(this)
            this.uploadReceipt = this.uploadReceipt.bind(this)
        }

        public async addReceipt(params: AddReceiptRequest): Promise<ItemReceipt> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/item/add-receipt`, JSON.stringify(params))
            return await resp.json() as ItemReceipt
        }

        public async analyzeBookshelf(params: AnalyzeBookshelfRequest): Promise<AnalyzeBookshelfResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/items/analyze-bookshelf`, JSON.stringify(params))
            return await resp.json() as AnalyzeBookshelfResponse
        }

        public async analyzeShelf(params: AnalyzeShelfRequest): Promise<AnalyzeShelfResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/items/analyze-shelf`, JSON.stringify(params))
            return await resp.json() as AnalyzeShelfResponse
        }

        public async batchCreate(params: BatchCreateRequest): Promise<BatchCreateResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/items/batch-create`, JSON.stringify(params))
            return await resp.json() as BatchCreateResponse
        }

        public async batchListByContainers(params: BatchListByContainersRequest): Promise<BatchListByContainersResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/items/batch/containers`, JSON.stringify(params))
            return await resp.json() as BatchListByContainersResponse
        }

        public async batchListByLocations(params: BatchListByLocationsRequest): Promise<BatchListByLocationsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/items/batch/locations`, JSON.stringify(params))
            return await resp.json() as BatchListByLocationsResponse
        }

        public async bulkAddTags(params: BulkAddTagsRequest): Promise<BulkAddTagsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/items/bulk-add-tags`, JSON.stringify(params))
            return await resp.json() as BulkAddTagsResponse
        }

        public async bulkConfirmLocation(params: BulkConfirmLocationRequest): Promise<BulkConfirmLocationResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/items/bulk-confirm-location`, JSON.stringify(params))
            return await resp.json() as BulkConfirmLocationResponse
        }

        public async bulkDelete(params: BulkDeleteRequest): Promise<void> {
            await this.baseClient.callTypedAPI("POST", `/items/bulk-delete`, JSON.stringify(params))
        }

        public async bulkUpdateLocation(params: BulkUpdateLocationRequest): Promise<BulkUpdateLocationResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/items/bulk-update-location`, JSON.stringify(params))
            return await resp.json() as BulkUpdateLocationResponse
        }

        public async confirmLocation(id: number): Promise<ConfirmLocationResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/items/${encodeURIComponent(id)}/confirm`)
            return await resp.json() as ConfirmLocationResponse
        }

        /**
         * Creates a new item in the inventory.
         */
        public async create(params: CreateItemRequest): Promise<Item> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/items`, JSON.stringify(params))
            return await resp.json() as Item
        }

        /**
         * Deletes an item from the inventory.
         */
        public async deleteItem(id: number): Promise<void> {
            await this.baseClient.callTypedAPI("DELETE", `/items/${encodeURIComponent(id)}`)
        }

        public async deleteReceipt(receiptId: number): Promise<DeleteReceiptResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("DELETE", `/item/receipt/${encodeURIComponent(receiptId)}`)
            return await resp.json() as DeleteReceiptResponse
        }

        public async expiring(params: ExpiringItemsRequest): Promise<ExpiringItemsResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:  params.limit === undefined ? undefined : String(params.limit),
                offset: params.offset === undefined ? undefined : String(params.offset),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/items/expiring`, undefined, {query})
            return await resp.json() as ExpiringItemsResponse
        }

        public async extractReceiptData(params: ExtractReceiptDataRequest): Promise<ExtractedReceiptData> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/item/extract-receipt-data`, JSON.stringify(params))
            return await resp.json() as ExtractedReceiptData
        }

        /**
         * Retrieves all favorite items.
         */
        public async favorites(params: FavoriteItemsRequest): Promise<FavoriteItemsResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:  params.limit === undefined ? undefined : String(params.limit),
                offset: params.offset === undefined ? undefined : String(params.offset),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/items/favorites`, undefined, {query})
            return await resp.json() as FavoriteItemsResponse
        }

        /**
         * Retrieves a single item by ID.
         */
        public async get(id: number): Promise<Item> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/items/${encodeURIComponent(id)}`)
            return await resp.json() as Item
        }

        public async getCategoryStatsByLocation(locationId: string): Promise<GetCategoryStatsByLocationResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/items/stats/${encodeURIComponent(locationId)}/categories`)
            return await resp.json() as GetCategoryStatsByLocationResponse
        }

        public async getConsumptionHistory(itemId: number): Promise<GetConsumptionHistoryResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/items/${encodeURIComponent(itemId)}/consumption-history`)
            return await resp.json() as GetConsumptionHistoryResponse
        }

        public async listByContainer(containerId: string): Promise<ListItemsByContainerResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/items/container/${encodeURIComponent(containerId)}`)
            return await resp.json() as ListItemsByContainerResponse
        }

        public async listByLocation(locationId: string): Promise<ListItemsByLocationResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/items/location/${encodeURIComponent(locationId)}`)
            return await resp.json() as ListItemsByLocationResponse
        }

        public async listByPlacedStatus(status: string, params: ListByPlacedStatusRequest): Promise<ListByPlacedStatusResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:  params.limit === undefined ? undefined : String(params.limit),
                offset: params.offset === undefined ? undefined : String(params.offset),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/items/placed/${encodeURIComponent(status)}`, undefined, {query})
            return await resp.json() as ListByPlacedStatusResponse
        }

        public async listReceipts(itemId: number): Promise<ListReceiptsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/item/${encodeURIComponent(itemId)}/receipts`)
            return await resp.json() as ListReceiptsResponse
        }

        public async lookupBarcode(upc: string): Promise<LookupBarcodeResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/items/barcode/${encodeURIComponent(upc)}`)
            return await resp.json() as LookupBarcodeResponse
        }

        public async lowStock(params: LowStockRequest): Promise<LowStockResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:  params.limit === undefined ? undefined : String(params.limit),
                offset: params.offset === undefined ? undefined : String(params.offset),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/items/low-stock`, undefined, {query})
            return await resp.json() as LowStockResponse
        }

        public async needsConfirmation(params: NeedsConfirmationRequest): Promise<NeedsConfirmationResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:  params.limit === undefined ? undefined : String(params.limit),
                offset: params.offset === undefined ? undefined : String(params.offset),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/items/needs-confirmation`, undefined, {query})
            return await resp.json() as NeedsConfirmationResponse
        }

        /**
         * Retrieves the 10 most recently added items.
         */
        public async recent(params: RecentItemsRequest): Promise<RecentItemsResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:  params.limit === undefined ? undefined : String(params.limit),
                offset: params.offset === undefined ? undefined : String(params.offset),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/items/recent`, undefined, {query})
            return await resp.json() as RecentItemsResponse
        }

        public async recordConsumption(itemId: number, params: RecordConsumptionRequest): Promise<RecordConsumptionResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/items/${encodeURIComponent(itemId)}/consume`, JSON.stringify(params))
            return await resp.json() as RecordConsumptionResponse
        }

        /**
         * Searches items by name, description, or tags.
         */
        public async search(params: SearchItemsRequest): Promise<SearchItemsResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:  params.limit === undefined ? undefined : String(params.limit),
                offset: params.offset === undefined ? undefined : String(params.offset),
                query:  params.query,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/items/search`, undefined, {query})
            return await resp.json() as SearchItemsResponse
        }

        /**
         * Toggles an item's favorite status.
         */
        public async toggleFavorite(id: number): Promise<Item> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/items/${encodeURIComponent(id)}/favorite`)
            return await resp.json() as Item
        }

        /**
         * Updates an item's properties.
         */
        public async update(id: number, params: UpdateItemRequest): Promise<Item> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PUT", `/items/${encodeURIComponent(id)}`, JSON.stringify(params))
            return await resp.json() as Item
        }

        /**
         * Updates just the quantity of an item quickly
         */
        public async updateQuantity(id: number, params: UpdateQuantityRequest): Promise<UpdateQuantityResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PATCH", `/items/${encodeURIComponent(id)}/quantity`, JSON.stringify(params))
            return await resp.json() as UpdateQuantityResponse
        }

        public async uploadPhoto(params: UploadPhotoRequest): Promise<UploadPhotoResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/items/upload-photo`, JSON.stringify(params))
            return await resp.json() as UploadPhotoResponse
        }

        public async uploadReceipt(params: UploadReceiptRequest): Promise<UploadReceiptResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/item/upload-receipt`, JSON.stringify(params))
            return await resp.json() as UploadReceiptResponse
        }
    }
}

export namespace location {
    export interface Container {
        id: number
        name: string
        items: ContainerItem[]
    }

    export interface ContainerItem {
        id: number
        name: string
        description?: string
        quantity: number
    }

    export interface CreateLocationRequest {
        name: string
    }

    export interface ListLocationsResponse {
        locations: LocationWithDetails[]
        containers: {
            id: number
            name: string
            locationId: number | null
            photoUrl: string | null
        }[]
    }

    export interface Location {
        id: number
        userId: string
        name: string
        createdAt: string
    }

    export interface LocationWithDetails {
        containers: Container[]
        unplacedItems: UnplacedItem[]
        id: number
        userId: string
        name: string
        createdAt: string
    }

    export interface UnplacedItem {
        id: number
        name: string
        description?: string
        quantity: number
    }

    export interface UpdateLocationRequest {
        name: string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.deleteLocation = this.deleteLocation.bind(this)
            this.list = this.list.bind(this)
            this.update = this.update.bind(this)
        }

        /**
         * Creates a new location for organizing items.
         */
        public async create(params: CreateLocationRequest): Promise<Location> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/locations`, JSON.stringify(params))
            return await resp.json() as Location
        }

        /**
         * Deletes a location and unlinks associated items.
         */
        public async deleteLocation(id: number): Promise<void> {
            await this.baseClient.callTypedAPI("DELETE", `/locations/${encodeURIComponent(id)}`)
        }

        /**
         * Retrieves all locations for the user.
         */
        public async list(): Promise<ListLocationsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/locations`)
            return await resp.json() as ListLocationsResponse
        }

        /**
         * Updates a location's name.
         */
        public async update(id: number, params: UpdateLocationRequest): Promise<Location> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PUT", `/locations/${encodeURIComponent(id)}`, JSON.stringify(params))
            return await resp.json() as Location
        }
    }
}

export namespace shopping {
    export interface AddToShoppingRequest {
        itemName: string
        quantity?: number
    }

    export interface ListShoppingResponse {
        items: ShoppingListItem[]
    }

    export interface LowStockItem {
        id: number
        name: string
        quantity: number
        minQuantity: number
        stockStatus: "low" | "out"
        locationName: string | null
    }

    export interface LowStockItemsResponse {
        items: LowStockItem[]
    }

    export interface ShoppingListItem {
        id: number
        userId: string
        itemName: string
        quantity: number
        addedAt: string
        isPurchased: boolean
        addedByUserId: string
        addedByEmail: string
        householdId: number
        updatedAt: string
    }

    export interface UpdateShoppingRequest {
        isPurchased?: boolean
        quantity?: number
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.add = this.add.bind(this)
            this.deleteItem = this.deleteItem.bind(this)
            this.list = this.list.bind(this)
            this.lowStockItems = this.lowStockItems.bind(this)
            this.update = this.update.bind(this)
        }

        public async add(params: AddToShoppingRequest): Promise<ShoppingListItem> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/shopping`, JSON.stringify(params))
            return await resp.json() as ShoppingListItem
        }

        public async deleteItem(id: number): Promise<void> {
            await this.baseClient.callTypedAPI("DELETE", `/shopping/${encodeURIComponent(id)}`)
        }

        public async list(): Promise<ListShoppingResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/shopping`)
            return await resp.json() as ListShoppingResponse
        }

        public async lowStockItems(): Promise<LowStockItemsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/shopping/low-stock`)
            return await resp.json() as LowStockItemsResponse
        }

        public async update(id: number, params: UpdateShoppingRequest): Promise<ShoppingListItem> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PATCH", `/shopping/${encodeURIComponent(id)}`, JSON.stringify(params))
            return await resp.json() as ShoppingListItem
        }
    }
}



function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ?  parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}

function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
      .replaceAll("=", "")
      .replaceAll("+", "-")
      .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "method" | "body" | "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}

// AuthDataGenerator is a function that returns a new instance of the authentication data required by this API
export type AuthDataGenerator = () =>
  | auth.AuthParams
  | Promise<auth.AuthParams | undefined>
  | undefined;

// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
    readonly authGenerator?: AuthDataGenerator

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (!BROWSER) {
            this.headers["User-Agent"] = "whereisit-inventory-app-9xhi-Generated-TS-Client (Encore/v1.51.11)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }

        // Setup an authentication data generator using the auth data token option
        if (options.auth !== undefined) {
            const auth = options.auth
            if (typeof auth === "function") {
                this.authGenerator = auth
            } else {
                this.authGenerator = () => auth
            }
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        let authData: auth.AuthParams | undefined;

        // If authorization data generator is present, call it and add the returned data to the request
        if (this.authGenerator) {
            const mayBePromise = this.authGenerator();
            if (mayBePromise instanceof Promise) {
                authData = await mayBePromise;
            } else {
                authData = mayBePromise;
            }
        }

        if (authData) {
            const data: CallParameters = {};

            data.headers = makeRecord<string, string>({
                authorization: authData.authorization,
            });

            return data;
        }

        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(method: string, path: string, body?: RequestInit["body"], params?: CallParameters): Promise<Response> {
        return this.callAPI(method, path, body, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(method: string, path: string, body?: RequestInit["body"], params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
            method,
            body: body ?? null,
        }

        // Merge our headers with any predefined headers
        init.headers = {...this.headers, ...init.headers, ...headers}

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                init.headers = {...init.headers, ...authData.headers};
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL+path+queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof(err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof(err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value:        'APIError',
            enumerable:   false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}
